apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: sb-api-scaler
  namespace: default
  labels:
    deploymentName: sb-api
spec:
  scaleTargetRef:
    deploymentName: sb-api
  pollingInterval: 30
  cooldownPeriod:  30
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.default.svc.cluster.local:9090
      metricName: access_frequency
      threshold: '100'
      query: sum(rate(http_server_requests_seconds_count{uri="/api"}[1m]))

