management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application:
        state: ${application.state:nj}
        environment: ${application.environment:dev}

